sonar.projectKey=angular-frontend
sonar.projectName=Angular Frontend
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/demo-frontend/lcov.info
sonar.sourceEncoding=UTF-8
